///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace browser5
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the browser5Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("d2d47dc8-f144-4735-903c-35505e15d31e")]
    public partial class browser5Repository : RepoGenBaseFolder
    {
        static browser5Repository instance = new browser5Repository();
        browser5RepositoryFolders.DubberAppFolder _dubber;
        browser5RepositoryFolders.DubberGoogleChromeAppFolder _dubbergooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the browser5Repository element repository.
        /// </summary>
        [RepositoryFolder("d2d47dc8-f144-4735-903c-35505e15d31e")]
        public static browser5Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public browser5Repository() 
            : base("browser5Repository", "/", null, 0, false, "d2d47dc8-f144-4735-903c-35505e15d31e", ".\\RepositoryImages\\browser5Repositoryd2d47dc8.rximgres")
        {
            _dubber = new browser5RepositoryFolders.DubberAppFolder(this);
            _dubbergooglechrome = new browser5RepositoryFolders.DubberGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d2d47dc8-f144-4735-903c-35505e15d31e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Dubber folder.
        /// </summary>
        [RepositoryFolder("3310cc9c-dfa0-42d3-9f1b-7fd2c59af9b1")]
        public virtual browser5RepositoryFolders.DubberAppFolder Dubber
        {
            get { return _dubber; }
        }

        /// <summary>
        /// The DubberGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("ac07cb24-b0c6-47c3-91b9-91b218a219f8")]
        public virtual browser5RepositoryFolders.DubberGoogleChromeAppFolder DubberGoogleChrome
        {
            get { return _dubbergooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class browser5RepositoryFolders
    {
        /// <summary>
        /// The DubberAppFolder folder.
        /// </summary>
        [RepositoryFolder("3310cc9c-dfa0-42d3-9f1b-7fd2c59af9b1")]
        public partial class DubberAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _useremailInfo;
            RepoItemInfo _userpasswordInfo;
            RepoItemInfo _submitbuttonInfo;
            RepoItemInfo _iconcogiconwhiteInfo;
            RepoItemInfo _dropdownlogoutInfo;

            /// <summary>
            /// Creates a new Dubber  folder.
            /// </summary>
            public DubberAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dubber", "/dom[@domain='tigers.dubber.net']", parentFolder, 30000, null, false, "3310cc9c-dfa0-42d3-9f1b-7fd2c59af9b1", "")
            {
                _useremailInfo = new RepoItemInfo(this, "UserEmail", ".//input[#'user_email']", 30000, null, "f4443993-9e9b-4746-9e1a-deb19d97bfa4");
                _userpasswordInfo = new RepoItemInfo(this, "UserPassword", ".//input[#'user_password']", 30000, null, "5c4192d1-dc86-48bf-bd85-a77e26e24778");
                _submitbuttonInfo = new RepoItemInfo(this, "SubmitButton", ".//input[#'submit_button']", 30000, null, "fa40ee0d-70c2-47e1-a3df-9b7a2c4b9170");
                _iconcogiconwhiteInfo = new RepoItemInfo(this, "IconCogIconWhite", ".//a[#'profile-ddt']/i", 30000, null, "240bde9c-ae4f-4062-b1e5-3e8200914f64");
                _dropdownlogoutInfo = new RepoItemInfo(this, "DropDownLogout", ".//a[#'drop_down_logout']", 30000, null, "699a4905-8092-422d-9db2-d8d45b06f855");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3310cc9c-dfa0-42d3-9f1b-7fd2c59af9b1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3310cc9c-dfa0-42d3-9f1b-7fd2c59af9b1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserEmail item.
            /// </summary>
            [RepositoryItem("f4443993-9e9b-4746-9e1a-deb19d97bfa4")]
            public virtual Ranorex.InputTag UserEmail
            {
                get
                {
                    return _useremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserEmail item info.
            /// </summary>
            [RepositoryItemInfo("f4443993-9e9b-4746-9e1a-deb19d97bfa4")]
            public virtual RepoItemInfo UserEmailInfo
            {
                get
                {
                    return _useremailInfo;
                }
            }

            /// <summary>
            /// The UserPassword item.
            /// </summary>
            [RepositoryItem("5c4192d1-dc86-48bf-bd85-a77e26e24778")]
            public virtual Ranorex.InputTag UserPassword
            {
                get
                {
                    return _userpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPassword item info.
            /// </summary>
            [RepositoryItemInfo("5c4192d1-dc86-48bf-bd85-a77e26e24778")]
            public virtual RepoItemInfo UserPasswordInfo
            {
                get
                {
                    return _userpasswordInfo;
                }
            }

            /// <summary>
            /// The SubmitButton item.
            /// </summary>
            [RepositoryItem("fa40ee0d-70c2-47e1-a3df-9b7a2c4b9170")]
            public virtual Ranorex.InputTag SubmitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("fa40ee0d-70c2-47e1-a3df-9b7a2c4b9170")]
            public virtual RepoItemInfo SubmitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }

            /// <summary>
            /// The IconCogIconWhite item.
            /// </summary>
            [RepositoryItem("240bde9c-ae4f-4062-b1e5-3e8200914f64")]
            public virtual Ranorex.ITag IconCogIconWhite
            {
                get
                {
                    return _iconcogiconwhiteInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IconCogIconWhite item info.
            /// </summary>
            [RepositoryItemInfo("240bde9c-ae4f-4062-b1e5-3e8200914f64")]
            public virtual RepoItemInfo IconCogIconWhiteInfo
            {
                get
                {
                    return _iconcogiconwhiteInfo;
                }
            }

            /// <summary>
            /// The DropDownLogout item.
            /// </summary>
            [RepositoryItem("699a4905-8092-422d-9db2-d8d45b06f855")]
            public virtual Ranorex.ATag DropDownLogout
            {
                get
                {
                    return _dropdownlogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DropDownLogout item info.
            /// </summary>
            [RepositoryItemInfo("699a4905-8092-422d-9db2-d8d45b06f855")]
            public virtual RepoItemInfo DropDownLogoutInfo
            {
                get
                {
                    return _dropdownlogoutInfo;
                }
            }
        }

        /// <summary>
        /// The DubberGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("ac07cb24-b0c6-47c3-91b9-91b218a219f8")]
        public partial class DubberGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new DubberGoogleChrome  folder.
            /// </summary>
            public DubberGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DubberGoogleChrome", "/form[@title='Dubber - Google Chrome']", parentFolder, 30000, null, true, "ac07cb24-b0c6-47c3-91b9-91b218a219f8", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "container[@accessiblename='Google Chrome']//tabpage[@accessiblename='Dubber']/button[@accessiblename='Close']", 30000, null, "96199071-8f86-447b-bd78-41a7c3da1f4d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ac07cb24-b0c6-47c3-91b9-91b218a219f8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ac07cb24-b0c6-47c3-91b9-91b218a219f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("96199071-8f86-447b-bd78-41a7c3da1f4d")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("96199071-8f86-447b-bd78-41a7c3da1f4d")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}