///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace calculator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the calculatorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("d6e78d9a-5300-4c30-917c-84c59353f615")]
    public partial class calculatorRepository : RepoGenBaseFolder
    {
        static calculatorRepository instance = new calculatorRepository();
        calculatorRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the calculatorRepository element repository.
        /// </summary>
        [RepositoryFolder("d6e78d9a-5300-4c30-917c-84c59353f615")]
        public static calculatorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public calculatorRepository() 
            : base("calculatorRepository", "/", null, 0, false, "d6e78d9a-5300-4c30-917c-84c59353f615", ".\\RepositoryImages\\calculatorRepositoryd6e78d9a.rximgres")
        {
            _calculator = new calculatorRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d6e78d9a-5300-4c30-917c-84c59353f615")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("9f1ccfa2-e779-4dff-925a-e8e72ee002cc")]
        public virtual calculatorRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class calculatorRepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("9f1ccfa2-e779-4dff-925a-e8e72ee002cc")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            calculatorRepositoryFolders.CalcFolder _calc;
            RepoItemInfo _viewInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/form[@title='Calculator']", parentFolder, 30000, null, true, "9f1ccfa2-e779-4dff-925a-e8e72ee002cc", "")
            {
                _calc = new calculatorRepositoryFolders.CalcFolder(this);
                _viewInfo = new RepoItemInfo(this, "View", "?/?/menuitem[@accessiblename='View']", 30000, null, "92a5d07d-e768-40ef-995f-2b0a833821d5");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "0e8f7553-64fa-4b6c-bd87-997a60a8d58e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9f1ccfa2-e779-4dff-925a-e8e72ee002cc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9f1ccfa2-e779-4dff-925a-e8e72ee002cc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The View item.
            /// </summary>
            [RepositoryItem("92a5d07d-e768-40ef-995f-2b0a833821d5")]
            public virtual Ranorex.MenuItem View
            {
                get
                {
                    return _viewInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The View item info.
            /// </summary>
            [RepositoryItemInfo("92a5d07d-e768-40ef-995f-2b0a833821d5")]
            public virtual RepoItemInfo ViewInfo
            {
                get
                {
                    return _viewInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("0e8f7553-64fa-4b6c-bd87-997a60a8d58e")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("0e8f7553-64fa-4b6c-bd87-997a60a8d58e")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Calc folder.
            /// </summary>
            [RepositoryFolder("3af4bb19-107c-4b5c-a9c3-62792fd61700")]
            public virtual calculatorRepositoryFolders.CalcFolder Calc
            {
                get { return _calc; }
            }
        }

        /// <summary>
        /// The CalcFolder folder.
        /// </summary>
        [RepositoryFolder("3af4bb19-107c-4b5c-a9c3-62792fd61700")]
        public partial class CalcFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button3Info;
            RepoItemInfo _button2Info;
            RepoItemInfo _buttonInfo;
            RepoItemInfo _button1Info;

            /// <summary>
            /// Creates a new Calc  folder.
            /// </summary>
            public CalcFolder(RepoGenBaseFolder parentFolder) :
                    base("Calc", "?/?/container[@instance='1']", parentFolder, 30000, null, false, "3af4bb19-107c-4b5c-a9c3-62792fd61700", "")
            {
                _button3Info = new RepoItemInfo(this, "Button3", "button[@controlid='121']", 30000, null, "f5c34454-00df-45d1-93b0-338914b35b52");
                _button2Info = new RepoItemInfo(this, "Button2", "button[@controlid='133']", 30000, null, "4ff2d549-0550-48d4-9d10-da12433cfcdb");
                _buttonInfo = new RepoItemInfo(this, "Button", "button[@controlid='139']", 30000, null, "c8fdae74-52e8-42e8-af01-38fe61abce43");
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlid='92']", 30000, null, "e0304fc3-73c7-4d6d-86c2-dc5af43baf45");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3af4bb19-107c-4b5c-a9c3-62792fd61700")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3af4bb19-107c-4b5c-a9c3-62792fd61700")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button3 item.
            /// </summary>
            [RepositoryItem("f5c34454-00df-45d1-93b0-338914b35b52")]
            public virtual Ranorex.Button Button3
            {
                get
                {
                    return _button3Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button3 item info.
            /// </summary>
            [RepositoryItemInfo("f5c34454-00df-45d1-93b0-338914b35b52")]
            public virtual RepoItemInfo Button3Info
            {
                get
                {
                    return _button3Info;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("4ff2d549-0550-48d4-9d10-da12433cfcdb")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("4ff2d549-0550-48d4-9d10-da12433cfcdb")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("c8fdae74-52e8-42e8-af01-38fe61abce43")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("c8fdae74-52e8-42e8-af01-38fe61abce43")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("e0304fc3-73c7-4d6d-86c2-dc5af43baf45")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("e0304fc3-73c7-4d6d-86c2-dc5af43baf45")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}