///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace binding
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the bindingRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("909bd924-33c4-468f-8c93-6204b94c03c9")]
    public partial class bindingRepository : RepoGenBaseFolder
    {
        static bindingRepository instance = new bindingRepository();
        bindingRepositoryFolders.DubberAppFolder _dubber;
        bindingRepositoryFolders.DropdownAppFolder _dropdown;

        /// <summary>
        /// Gets the singleton class instance representing the bindingRepository element repository.
        /// </summary>
        [RepositoryFolder("909bd924-33c4-468f-8c93-6204b94c03c9")]
        public static bindingRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public bindingRepository() 
            : base("bindingRepository", "/", null, 0, false, "909bd924-33c4-468f-8c93-6204b94c03c9", ".\\RepositoryImages\\bindingRepository909bd924.rximgres")
        {
            _dubber = new bindingRepositoryFolders.DubberAppFolder(this);
            _dropdown = new bindingRepositoryFolders.DropdownAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("909bd924-33c4-468f-8c93-6204b94c03c9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Dubber folder.
        /// </summary>
        [RepositoryFolder("34ee9257-7cdc-4aef-9231-37c20522d951")]
        public virtual bindingRepositoryFolders.DubberAppFolder Dubber
        {
            get { return _dubber; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("1039ec72-150a-4964-b24e-aed0168fc281")]
        public virtual bindingRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class bindingRepositoryFolders
    {
        /// <summary>
        /// The DubberAppFolder folder.
        /// </summary>
        [RepositoryFolder("34ee9257-7cdc-4aef-9231-37c20522d951")]
        public partial class DubberAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _useremailInfo;
            RepoItemInfo _userpasswordInfo;
            RepoItemInfo _submitbuttonInfo;
            RepoItemInfo _newaccountInfo;
            RepoItemInfo _accountnameInfo;
            RepoItemInfo _accountdubberaddressInfo;
            RepoItemInfo _profileddtInfo;
            RepoItemInfo _dropdownlogoutInfo;
            RepoItemInfo _accountexternalreferenceInfo;
            RepoItemInfo _accountaddressattributesaddressInfo;

            /// <summary>
            /// Creates a new Dubber  folder.
            /// </summary>
            public DubberAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dubber", "/dom[@domain='tigers.dubber.net']", parentFolder, 30000, null, false, "34ee9257-7cdc-4aef-9231-37c20522d951", "")
            {
                _useremailInfo = new RepoItemInfo(this, "UserEmail", ".//input[#'user_email']", 30000, null, "320972ab-0e5e-440a-bf34-b092ae9160f5");
                _userpasswordInfo = new RepoItemInfo(this, "UserPassword", ".//input[#'user_password']", 30000, null, "c0123477-719e-45c0-8937-a74d168b86ae");
                _submitbuttonInfo = new RepoItemInfo(this, "SubmitButton", ".//input[#'submit_button']", 30000, null, "4ab177de-0bd0-4837-9be6-4a209a2c6116");
                _newaccountInfo = new RepoItemInfo(this, "NewAccount", ".//a[#'new_account']", 30000, null, "281e15b0-26f8-47a3-bc61-93f58b352bd9");
                _accountnameInfo = new RepoItemInfo(this, "AccountName", ".//input[#'account_name']", 30000, null, "841ef3f1-1c39-4c58-9357-1e08d0b8583c");
                _accountdubberaddressInfo = new RepoItemInfo(this, "AccountDubberAddress", ".//input[#'account_dubber_address']", 30000, null, "8dd9255c-4eeb-471c-9ee4-89e2e099e439");
                _profileddtInfo = new RepoItemInfo(this, "ProfileDdt", ".//a[#'profile-ddt']", 30000, null, "d2f74ab4-7842-4e1d-a8ea-01122d76097c");
                _dropdownlogoutInfo = new RepoItemInfo(this, "DropDownLogout", ".//a[#'drop_down_logout']", 30000, null, "9b14b159-c73d-45c9-b88e-143ca3d7ebd9");
                _accountexternalreferenceInfo = new RepoItemInfo(this, "AccountExternalReference", ".//input[#'account_external_reference']", 30000, null, "2e61cc49-0b32-41b8-bed6-bd0a4ffee59f");
                _accountaddressattributesaddressInfo = new RepoItemInfo(this, "AccountAddressAttributesAddress", ".//input[#'account_address_attributes_address']", 30000, null, "548f904d-7741-40f9-9a5b-7face322a72a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("34ee9257-7cdc-4aef-9231-37c20522d951")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("34ee9257-7cdc-4aef-9231-37c20522d951")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserEmail item.
            /// </summary>
            [RepositoryItem("320972ab-0e5e-440a-bf34-b092ae9160f5")]
            public virtual Ranorex.InputTag UserEmail
            {
                get
                {
                    return _useremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserEmail item info.
            /// </summary>
            [RepositoryItemInfo("320972ab-0e5e-440a-bf34-b092ae9160f5")]
            public virtual RepoItemInfo UserEmailInfo
            {
                get
                {
                    return _useremailInfo;
                }
            }

            /// <summary>
            /// The UserPassword item.
            /// </summary>
            [RepositoryItem("c0123477-719e-45c0-8937-a74d168b86ae")]
            public virtual Ranorex.InputTag UserPassword
            {
                get
                {
                    return _userpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPassword item info.
            /// </summary>
            [RepositoryItemInfo("c0123477-719e-45c0-8937-a74d168b86ae")]
            public virtual RepoItemInfo UserPasswordInfo
            {
                get
                {
                    return _userpasswordInfo;
                }
            }

            /// <summary>
            /// The SubmitButton item.
            /// </summary>
            [RepositoryItem("4ab177de-0bd0-4837-9be6-4a209a2c6116")]
            public virtual Ranorex.InputTag SubmitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("4ab177de-0bd0-4837-9be6-4a209a2c6116")]
            public virtual RepoItemInfo SubmitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }

            /// <summary>
            /// The NewAccount item.
            /// </summary>
            [RepositoryItem("281e15b0-26f8-47a3-bc61-93f58b352bd9")]
            public virtual Ranorex.ATag NewAccount
            {
                get
                {
                    return _newaccountInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NewAccount item info.
            /// </summary>
            [RepositoryItemInfo("281e15b0-26f8-47a3-bc61-93f58b352bd9")]
            public virtual RepoItemInfo NewAccountInfo
            {
                get
                {
                    return _newaccountInfo;
                }
            }

            /// <summary>
            /// The AccountName item.
            /// </summary>
            [RepositoryItem("841ef3f1-1c39-4c58-9357-1e08d0b8583c")]
            public virtual Ranorex.InputTag AccountName
            {
                get
                {
                    return _accountnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountName item info.
            /// </summary>
            [RepositoryItemInfo("841ef3f1-1c39-4c58-9357-1e08d0b8583c")]
            public virtual RepoItemInfo AccountNameInfo
            {
                get
                {
                    return _accountnameInfo;
                }
            }

            /// <summary>
            /// The AccountDubberAddress item.
            /// </summary>
            [RepositoryItem("8dd9255c-4eeb-471c-9ee4-89e2e099e439")]
            public virtual Ranorex.InputTag AccountDubberAddress
            {
                get
                {
                    return _accountdubberaddressInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountDubberAddress item info.
            /// </summary>
            [RepositoryItemInfo("8dd9255c-4eeb-471c-9ee4-89e2e099e439")]
            public virtual RepoItemInfo AccountDubberAddressInfo
            {
                get
                {
                    return _accountdubberaddressInfo;
                }
            }

            /// <summary>
            /// The ProfileDdt item.
            /// </summary>
            [RepositoryItem("d2f74ab4-7842-4e1d-a8ea-01122d76097c")]
            public virtual Ranorex.ATag ProfileDdt
            {
                get
                {
                    return _profileddtInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ProfileDdt item info.
            /// </summary>
            [RepositoryItemInfo("d2f74ab4-7842-4e1d-a8ea-01122d76097c")]
            public virtual RepoItemInfo ProfileDdtInfo
            {
                get
                {
                    return _profileddtInfo;
                }
            }

            /// <summary>
            /// The DropDownLogout item.
            /// </summary>
            [RepositoryItem("9b14b159-c73d-45c9-b88e-143ca3d7ebd9")]
            public virtual Ranorex.ATag DropDownLogout
            {
                get
                {
                    return _dropdownlogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DropDownLogout item info.
            /// </summary>
            [RepositoryItemInfo("9b14b159-c73d-45c9-b88e-143ca3d7ebd9")]
            public virtual RepoItemInfo DropDownLogoutInfo
            {
                get
                {
                    return _dropdownlogoutInfo;
                }
            }

            /// <summary>
            /// The AccountExternalReference item.
            /// </summary>
            [RepositoryItem("2e61cc49-0b32-41b8-bed6-bd0a4ffee59f")]
            public virtual Ranorex.InputTag AccountExternalReference
            {
                get
                {
                    return _accountexternalreferenceInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountExternalReference item info.
            /// </summary>
            [RepositoryItemInfo("2e61cc49-0b32-41b8-bed6-bd0a4ffee59f")]
            public virtual RepoItemInfo AccountExternalReferenceInfo
            {
                get
                {
                    return _accountexternalreferenceInfo;
                }
            }

            /// <summary>
            /// The AccountAddressAttributesAddress item.
            /// </summary>
            [RepositoryItem("548f904d-7741-40f9-9a5b-7face322a72a")]
            public virtual Ranorex.InputTag AccountAddressAttributesAddress
            {
                get
                {
                    return _accountaddressattributesaddressInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountAddressAttributesAddress item info.
            /// </summary>
            [RepositoryItemInfo("548f904d-7741-40f9-9a5b-7face322a72a")]
            public virtual RepoItemInfo AccountAddressAttributesAddressInfo
            {
                get
                {
                    return _accountaddressattributesaddressInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("1039ec72-150a-4964-b24e-aed0168fc281")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "1039ec72-150a-4964-b24e-aed0168fc281", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1039ec72-150a-4964-b24e-aed0168fc281")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1039ec72-150a-4964-b24e-aed0168fc281")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}