///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace binding
{
    public partial class Second
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public static class RandomFactory 
            {
        		private static Random r = new Random();
        
        public static int getNextRandomNumber()
        {
           return r.Next();
        }
        
        public static int getNextRandomNumber(int maxValue)
        {
           return r.Next(maxValue);
        }
        
        public static int getNextRandomNumber(int minValue, int maxValue) 
        {
           return r.Next(minValue, maxValue);
        }
        
        public static string getRandomString(int minLength, int maxLength, bool isInitialCaps)
        {
           Random r = new Random();
           
           int length = getNextRandomNumber(minLength, maxLength);
           
           char[] characters = {'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'};
           
           StringBuilder sb = new StringBuilder();
           
           for (int i = 0; i < length; i++) {
              sb.Append(characters[r.Next(26)]);
           }
           
           return isInitialCaps ? sb.ToString().Substring(0,1).ToUpper() + sb.ToString().Substring(1) : sb.ToString();
        }
}
          }
    }
        public void Recording1_Open_Browser()
        {
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://tigers.dubber.net/login' with browser 'chrome' in normal mode.");
            Host.Local.OpenBrowser("https://tigers.dubber.net/login", "chrome", "", false, false, false, false, false);
        }

        public void Mouse_Click_Close()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberGoogleChrome.Close' at 14;16.", repo.DubberGoogleChrome.CloseInfo);
            repo.DubberGoogleChrome.Close.Click("14;16");
        }

        public void Mouse_Click_DropDownLogout()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.DropDownLogout' at 79;13.", repo.Dubber.DropDownLogoutInfo);
            repo.Dubber.DropDownLogout.Click("79;13");
        }

        public void Mouse_Click_ProfileDdt()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.ProfileDdt' at 31;18.", repo.Dubber.ProfileDdtInfo);
            repo.Dubber.ProfileDdt.Click("31;18");
        }

        public void Key_Sequence_AccountDubberAddress()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'seee' with focus on 'Dubber.AccountDubberAddress'.", repo.Dubber.AccountDubberAddressInfo);
            repo.Dubber.AccountDubberAddress.PressKeys("seee", 100);
        }

        public void Mouse_Click_AccountDubberAddress()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.AccountDubberAddress' at 41;16.", repo.Dubber.AccountDubberAddressInfo);
            repo.Dubber.AccountDubberAddress.Click("41;16");
        }

        public void Key_Sequence_AccountName()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'seee' with focus on 'Dubber.AccountName'.", repo.Dubber.AccountNameInfo);
           repo.Dubber.AccountName.PressKeys("seee",100);
        }

        public void Mouse_Click_AccountName()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.AccountName' at 44;14.", repo.Dubber.AccountNameInfo);
            repo.Dubber.AccountName.Click("44;14");
        }

        public void Mouse_Click_NewAccount()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.NewAccount' at 69;19.", repo.Dubber.NewAccountInfo);
            repo.Dubber.NewAccount.Click("69;19");
        }

        public void Mouse_Click_SubmitButton()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.SubmitButton' at 36;22.", repo.Dubber.SubmitButtonInfo);
            repo.Dubber.SubmitButton.Click("36;22");
        }

        public void Key_Sequence_UserPassword()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}P{RShiftKey up}{RShiftKey down}@{RShiftKey up}ssword1' with focus on 'Dubber.UserPassword'.", repo.Dubber.UserPasswordInfo);
            repo.Dubber.UserPassword.PressKeys("{RShiftKey down}P{RShiftKey up}{RShiftKey down}@{RShiftKey up}ssword1", 100);
        }

        public void Mouse_Click_UserPassword()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.UserPassword' at 166;31.", repo.Dubber.UserPasswordInfo);
            repo.Dubber.UserPassword.Click("166;31");
        }

        public void Key_Sequence_UserEmail()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'qa{RShiftKey down}+{RShiftKey up}4{RShiftKey down}@{RShiftKey up}dubber.net' with focus on 'Dubber.UserEmail'.", repo.Dubber.UserEmailInfo);
            repo.Dubber.UserEmail.PressKeys("qa{RShiftKey down}+{RShiftKey up}4{RShiftKey down}@{RShiftKey up}dubber.net", 100);
        }

        public void Mouse_Click_UserEmail()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.UserEmail' at 173;17.", repo.Dubber.UserEmailInfo);
            repo.Dubber.UserEmail.Click("173;17");
        }

    }
}
 