///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace binding
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The st recording.
    /// </summary>
    [TestModule("37ac936a-efd4-4fab-97ef-229d478f430c", ModuleType.Recording, 1)]
    public partial class St : ITestModule
    {
        /// <summary>
        /// Holds an instance of the bindingRepository repository.
        /// </summary>
        public static bindingRepository repo = bindingRepository.Instance;

        static St instance = new St();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public St()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static St Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 50;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://tigers.dubber.net/login' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://tigers.dubber.net/login", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.UserEmail' at 121;19.", repo.Dubber.UserEmailInfo, new RecordItemIndex(1));
            repo.Dubber.UserEmail.Click("121;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'qa' with focus on 'Dubber.UserEmail'.", repo.Dubber.UserEmailInfo, new RecordItemIndex(2));
            repo.Dubber.UserEmail.PressKeys("qa", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 119;9.", repo.Dropdown.SelfInfo, new RecordItemIndex(3));
            repo.Dropdown.Self.Click("119;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.UserPassword' at 121;18.", repo.Dubber.UserPasswordInfo, new RecordItemIndex(4));
            repo.Dubber.UserPassword.Click("121;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}P{RShiftKey up}{RShiftKey down}@{RShiftKey up}ssword1' with focus on 'Dubber.UserPassword'.", repo.Dubber.UserPasswordInfo, new RecordItemIndex(5));
            repo.Dubber.UserPassword.PressKeys("{RShiftKey down}P{RShiftKey up}{RShiftKey down}@{RShiftKey up}ssword1", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.SubmitButton' at 70;26.", repo.Dubber.SubmitButtonInfo, new RecordItemIndex(6));
            repo.Dubber.SubmitButton.Click("70;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.NewAccount' at 90;16.", repo.Dubber.NewAccountInfo, new RecordItemIndex(7));
            repo.Dubber.NewAccount.Click("90;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.AccountName' at 62;17.", repo.Dubber.AccountNameInfo, new RecordItemIndex(8));
            repo.Dubber.AccountName.Click("62;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'seema' with focus on 'Dubber.AccountName'.", repo.Dubber.AccountNameInfo, new RecordItemIndex(9));
            repo.Dubber.AccountName.PressKeys("seema", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.AccountDubberAddress' at 65;11.", repo.Dubber.AccountDubberAddressInfo, new RecordItemIndex(10));
            repo.Dubber.AccountDubberAddress.Click("65;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 's' with focus on 'Dubber.AccountDubberAddress'.", repo.Dubber.AccountDubberAddressInfo, new RecordItemIndex(11));
            repo.Dubber.AccountDubberAddress.PressKeys("s", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'r' with focus on 'Dubber.AccountDubberAddress'.", repo.Dubber.AccountDubberAddressInfo, new RecordItemIndex(12));
            repo.Dubber.AccountDubberAddress.PressKeys("r", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'kk' with focus on 'Dubber.AccountDubberAddress'.", repo.Dubber.AccountDubberAddressInfo, new RecordItemIndex(13));
            repo.Dubber.AccountDubberAddress.PressKeys("kk", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.ProfileDdt' at 40;15.", repo.Dubber.ProfileDdtInfo, new RecordItemIndex(14));
            repo.Dubber.ProfileDdt.Click("40;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.DropDownLogout' at 101;6.", repo.Dubber.DropDownLogoutInfo, new RecordItemIndex(15));
            repo.Dubber.DropDownLogout.Click("101;6");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
