///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace imap1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the imap1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("014c5781-293a-4e4b-ae00-6de96e321183")]
    public partial class imap1Repository : RepoGenBaseFolder
    {
        static imap1Repository instance = new imap1Repository();

        /// <summary>
        /// Gets the singleton class instance representing the imap1Repository element repository.
        /// </summary>
        [RepositoryFolder("014c5781-293a-4e4b-ae00-6de96e321183")]
        public static imap1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public imap1Repository() 
            : base("imap1Repository", "/", null, 0, false, "014c5781-293a-4e4b-ae00-6de96e321183", ".\\RepositoryImages\\imap1Repository014c5781.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("014c5781-293a-4e4b-ae00-6de96e321183")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class imap1RepositoryFolders
    {
    }
#pragma warning restore 0436
}